import { Division, Position, OfficeSettings, User, AttendanceRecord } from '../types';

export const INITIAL_DIVISIONS: Division[] = [
  { id: 'div-1', name: 'Teknologi Informasi (IT)', code: 'IT', description: 'Pengembangan Perangkat Lunak & Infrastruktur' },
  { id: 'div-2', name: 'Keuangan & Akuntansi', code: 'FIN', description: 'Pengelolaan Keuangan & Pembukuan' },
  { id: 'div-3', name: 'Sumber Daya Manusia (HR)', code: 'HR', description: 'Perekrutan & Manajemen SDM' },
  { id: 'div-4', name: 'Pemasaran & Media', code: 'MKT', description: 'Pemasaran Digital & Branding' },
  { id: 'div-5', name: 'Operasional', code: 'OPS', description: 'Layanan Pelanggan & Logistik' },
];

export const INITIAL_POSITIONS: Position[] = [
  { id: 'pos-1', title: 'Head of Department', level: 'Managerial', description: 'Penanggung Jawab Divisi' },
  { id: 'pos-2', title: 'Senior Software Engineer', level: 'Senior', description: 'Pengembang Sistem Senior' },
  { id: 'pos-3', title: 'Financial Analyst', level: 'Staff', description: 'Analis Keuangan' },
  { id: 'pos-4', title: 'HR Generalist', level: 'Staff', description: 'Perekrutan & Hubungan Karyawan' },
  { id: 'pos-5', title: 'Digital Marketing Specialist', level: 'Staff', description: 'Pengelola Media Sosial & Iklan' },
];

export const DEFAULT_OFFICE_SETTINGS: OfficeSettings = {
  officeName: 'Kantor Pusat Jakarta CBD',
  latitude: -6.175392,
  longitude: 106.827153,
  radiusMeters: 100,
  address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat 10110',
  workStartTime: '08:00',
  workEndTime: '17:00',
  lateToleranceMinutes: 15,
  workDays: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'],
  branches: [
    {
      id: 'branch-surabaya',
      officeName: 'Cabang Surabaya HR Muhammad',
      latitude: -7.289123,
      longitude: 112.695421,
      radiusMeters: 150,
      address: 'Jl. HR Muhammad No. 88, Dukuh Pakis, Surabaya, Jawa Timur 60225',
    },
    {
      id: 'branch-bandung',
      officeName: 'Cabang Bandung Dago Tech',
      latitude: -6.890123,
      longitude: 107.610234,
      radiusMeters: 120,
      address: 'Jl. Ir. H. Juanda No. 120, Dago, Bandung, Jawa Barat 40132',
    },
  ],
};

// Initial Users: Admin and Staff Karyawan
export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    nik: 'ADM001',
    username: 'admin',
    password: 'admin123',
    name: 'Administrator Perusahaan',
    email: 'admin@perusahaan.com',
    gender: 'L',
    divisionId: 'div-1',
    divisionName: 'Teknologi Informasi (IT)',
    positionId: 'pos-1',
    positionName: 'Head of Department',
    phone: '081234567890',
    status: 'aktif',
    role: 'admin',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-01',
  },
  {
    id: 'user-budi',
    nik: 'EMP001',
    username: 'budi',
    password: 'user123',
    name: 'Budi Santoso',
    email: 'budi.santoso@perusahaan.com',
    gender: 'L',
    divisionId: 'div-1',
    divisionName: 'Teknologi Informasi (IT)',
    positionId: 'pos-2',
    positionName: 'Senior Software Engineer',
    phone: '081234567891',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-05',
  },
  {
    id: 'user-siti',
    nik: 'EMP002',
    username: 'siti',
    password: 'user123',
    name: 'Siti Rahmawati',
    email: 'siti.rahma@perusahaan.com',
    gender: 'P',
    divisionId: 'div-2',
    divisionName: 'Keuangan & Akuntansi',
    positionId: 'pos-3',
    positionName: 'Financial Analyst',
    phone: '081234567892',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-10',
  },
  {
    id: 'user-ahmad',
    nik: 'EMP003',
    username: 'ahmad',
    password: 'user123',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@perusahaan.com',
    gender: 'L',
    divisionId: 'div-3',
    divisionName: 'Sumber Daya Manusia (HR)',
    positionId: 'pos-4',
    positionName: 'HR Generalist',
    phone: '081234567893',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-12',
  },
  {
    id: 'user-dewi',
    nik: 'EMP004',
    username: 'dewi',
    password: 'user123',
    name: 'Dewi Sartika',
    email: 'dewi.sartika@perusahaan.com',
    gender: 'P',
    divisionId: 'div-4',
    divisionName: 'Pemasaran & Media',
    positionId: 'pos-5',
    positionName: 'Digital Marketing Specialist',
    phone: '081234567894',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-15',
  },
  {
    id: 'user-eko',
    nik: 'EMP005',
    username: 'eko',
    password: 'user123',
    name: 'Eko Prasetyo',
    email: 'eko.prasetyo@perusahaan.com',
    gender: 'L',
    divisionId: 'div-5',
    divisionName: 'Operasional',
    positionId: 'pos-1',
    positionName: 'Head of Department',
    phone: '081234567895',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: [],
    faceRegistered: false,
    createdAt: '2025-01-18',
  },
];

// Helper to get formatted date string with day offset in Jakarta timezone
function getDateOffsetStr(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() - offsetDays);
  return new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Jakarta' }).format(d);
}

// Initial attendance records (used for cold-start and when Firestore reaches free-tier read limits)
export function getInitialAttendances(): AttendanceRecord[] {
  const d0 = getDateOffsetStr(0); // Hari ini
  const d1 = getDateOffsetStr(1); // Kemarin
  const d2 = getDateOffsetStr(2); // 2 hari lalu
  const d3 = getDateOffsetStr(3); // 3 hari lalu

  return [
    // HARI INI - MASUK & PULANG
    {
      id: 'att-init-01',
      employeeId: 'user-budi',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'masuk',
      date: d0,
      serverTime: '07:48:15',
      latitude: -6.175401,
      longitude: 106.827165,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 14,
      faceMatchScore: 97.4,
      status: 'berhasil',
      keterangan: 'Tepat Waktu (Radius 14m)',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 28000000,
    },
    {
      id: 'att-init-02',
      employeeId: 'user-siti',
      employeeName: 'Siti Rahmawati',
      nik: 'EMP002',
      divisionName: 'Keuangan & Akuntansi',
      positionName: 'Financial Analyst',
      type: 'masuk',
      date: d0,
      serverTime: '08:22:40',
      latitude: -6.175420,
      longitude: 106.827180,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 22,
      faceMatchScore: 94.8,
      status: 'berhasil',
      keterangan: 'Terlambat 7 Menit (Toleransi 15m)',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 25000000,
    },
    {
      id: 'att-init-03',
      employeeId: 'user-ahmad',
      employeeName: 'Ahmad Fauzi',
      nik: 'EMP003',
      divisionName: 'Sumber Daya Manusia (HR)',
      positionName: 'HR Generalist',
      type: 'masuk',
      date: d0,
      serverTime: '07:55:10',
      latitude: -6.175380,
      longitude: 106.827140,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 18,
      faceMatchScore: 96.1,
      status: 'berhasil',
      keterangan: 'Tepat Waktu (Radius 18m)',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 27000000,
    },
    {
      id: 'att-init-04',
      employeeId: 'user-dewi',
      employeeName: 'Dewi Sartika',
      nik: 'EMP004',
      divisionName: 'Pemasaran & Media',
      positionName: 'Digital Marketing Specialist',
      type: 'masuk',
      date: d0,
      serverTime: '08:05:32',
      latitude: -6.175390,
      longitude: 106.827150,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 10,
      faceMatchScore: 98.2,
      status: 'berhasil',
      keterangan: 'Tepat Waktu (Radius 10m)',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 26000000,
    },
    {
      id: 'att-init-05',
      employeeId: 'user-budi',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'pulang',
      date: d0,
      serverTime: '17:08:12',
      latitude: -6.175410,
      longitude: 106.827160,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 16,
      faceMatchScore: 96.5,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal (Radius 16m)',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 3600000,
    },
    {
      id: 'att-init-06',
      employeeId: 'user-ahmad',
      employeeName: 'Ahmad Fauzi',
      nik: 'EMP003',
      divisionName: 'Sumber Daya Manusia (HR)',
      positionName: 'HR Generalist',
      type: 'pulang',
      date: d0,
      serverTime: '17:15:45',
      latitude: -6.175385,
      longitude: 106.827145,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 15,
      faceMatchScore: 95.7,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal (Radius 15m)',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 3000000,
    },

    // KEMARIN (d1)
    {
      id: 'att-init-07',
      employeeId: 'user-budi',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'masuk',
      date: d1,
      serverTime: '07:51:20',
      latitude: -6.175395,
      longitude: 106.827155,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 12,
      faceMatchScore: 98.1,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 86400000,
    },
    {
      id: 'att-init-08',
      employeeId: 'user-budi',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'pulang',
      date: d1,
      serverTime: '17:05:40',
      latitude: -6.175405,
      longitude: 106.827160,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 15,
      faceMatchScore: 96.9,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 60000000,
    },
    {
      id: 'att-init-09',
      employeeId: 'user-siti',
      employeeName: 'Siti Rahmawati',
      nik: 'EMP002',
      divisionName: 'Keuangan & Akuntansi',
      positionName: 'Financial Analyst',
      type: 'masuk',
      date: d1,
      serverTime: '07:46:12',
      latitude: -6.175415,
      longitude: 106.827170,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 20,
      faceMatchScore: 95.3,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 87000000,
    },
    {
      id: 'att-init-10',
      employeeId: 'user-siti',
      employeeName: 'Siti Rahmawati',
      nik: 'EMP002',
      divisionName: 'Keuangan & Akuntansi',
      positionName: 'Financial Analyst',
      type: 'pulang',
      date: d1,
      serverTime: '17:12:00',
      latitude: -6.175410,
      longitude: 106.827165,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 18,
      faceMatchScore: 94.7,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 59000000,
    },
    {
      id: 'att-init-11',
      employeeId: 'user-dewi',
      employeeName: 'Dewi Sartika',
      nik: 'EMP004',
      divisionName: 'Pemasaran & Media',
      positionName: 'Digital Marketing Specialist',
      type: 'masuk',
      date: d1,
      serverTime: '08:35:10',
      latitude: -6.175420,
      longitude: 106.827180,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 25,
      faceMatchScore: 93.8,
      status: 'berhasil',
      keterangan: 'Terlambat 20 Menit',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 84000000,
    },
    {
      id: 'att-init-12',
      employeeId: 'user-dewi',
      employeeName: 'Dewi Sartika',
      nik: 'EMP004',
      divisionName: 'Pemasaran & Media',
      positionName: 'Digital Marketing Specialist',
      type: 'pulang',
      date: d1,
      serverTime: '17:30:15',
      latitude: -6.175400,
      longitude: 106.827150,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 14,
      faceMatchScore: 96.0,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 58000000,
    },

    // 2 & 3 HARI LALU (d2, d3)
    {
      id: 'att-init-13',
      employeeId: 'user-eko',
      employeeName: 'Eko Prasetyo',
      nik: 'EMP005',
      divisionName: 'Operasional',
      positionName: 'Head of Department',
      type: 'masuk',
      date: d2,
      serverTime: '07:44:30',
      latitude: -6.175390,
      longitude: 106.827150,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 10,
      faceMatchScore: 97.8,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
      photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 172800000,
    },
    {
      id: 'att-init-14',
      employeeId: 'user-eko',
      employeeName: 'Eko Prasetyo',
      nik: 'EMP005',
      divisionName: 'Operasional',
      positionName: 'Head of Department',
      type: 'pulang',
      date: d2,
      serverTime: '17:00:20',
      latitude: -6.175395,
      longitude: 106.827155,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 11,
      faceMatchScore: 96.2,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
      photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 145000000,
    },
    {
      id: 'att-init-15',
      employeeId: 'user-ahmad',
      employeeName: 'Ahmad Fauzi',
      nik: 'EMP003',
      divisionName: 'Sumber Daya Manusia (HR)',
      positionName: 'HR Generalist',
      type: 'masuk',
      date: d3,
      serverTime: '07:58:10',
      latitude: -6.175385,
      longitude: 106.827145,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 15,
      faceMatchScore: 97.0,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 259200000,
    },
    {
      id: 'att-init-16',
      employeeId: 'user-ahmad',
      employeeName: 'Ahmad Fauzi',
      nik: 'EMP003',
      divisionName: 'Sumber Daya Manusia (HR)',
      positionName: 'HR Generalist',
      type: 'pulang',
      date: d3,
      serverTime: '17:10:30',
      latitude: -6.175390,
      longitude: 106.827150,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 13,
      faceMatchScore: 95.8,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      timestamp: Date.now() - 230000000,
    },
  ];
}
