import { Division, Position, OfficeSettings, User, AttendanceRecord } from '../types';
import { generateSeedFaceDescriptor } from './faceAI';

export const INITIAL_DIVISIONS: Division[] = [
  { id: 'div-1', name: 'Teknologi Informasi (IT)', code: 'IT', description: 'Pengembangan Perangkat Lunak & Infrastruktur' },
  { id: 'div-2', name: 'Keuangan & Akuntansi', code: 'FIN', description: 'Pengelolaan Keuangan & Pembukuan' },
  { id: 'div-3', name: 'Sumber Daya Manusia (HR)', code: 'HR', description: 'Perekrutan & Manajemen SDM' },
  { id: 'div-4', name: 'Pemasaran & Media', code: 'MKT', description: 'Pemasaran Digital & Branding' },
  { id: 'div-5', name: 'Operasional', code: 'OPS', description: 'Layanan Pelanggan & Logistik' },
];

export const INITIAL_POSITIONS: Position[] = [
  { id: 'pos-1', title: 'Head of Department', level: 'Managerial', description: 'Penanggung Jawab Divisi' },
  { id: 'pos-2', title: 'Senior Software Engineer', level: 'Senior', description: 'Pengembang Sistem Senior' },
  { id: 'pos-3', title: 'Financial Analyst', level: 'Staff', description: 'Analis Keuangan' },
  { id: 'pos-4', title: 'HR Generalist', level: 'Staff', description: 'Perekrutan & Hubungan Karyawan' },
  { id: 'pos-5', title: 'Digital Marketing Specialist', level: 'Staff', description: 'Pengelola Media Sosial & Iklan' },
];

export const DEFAULT_OFFICE_SETTINGS: OfficeSettings = {
  officeName: 'Kantor Pusat Jakarta CBD',
  latitude: -6.175392,
  longitude: 106.827153,
  radiusMeters: 100,
  address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat 10110',
  workStartTime: '08:00',
  workEndTime: '17:00',
  lateToleranceMinutes: 15,
  workDays: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'],
  branches: [
    {
      id: 'branch-surabaya',
      officeName: 'Cabang Surabaya HR Muhammad',
      latitude: -7.289123,
      longitude: 112.695421,
      radiusMeters: 150,
      address: 'Jl. HR Muhammad No. 88, Dukuh Pakis, Surabaya, Jawa Timur 60225',
    },
    {
      id: 'branch-bandung',
      officeName: 'Cabang Bandung Dago Tech',
      latitude: -6.890123,
      longitude: 107.610234,
      radiusMeters: 120,
      address: 'Jl. Ir. H. Juanda No. 120, Dago, Bandung, Jawa Barat 40132',
    },
  ],
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    nik: 'ADM001',
    username: 'admin',
    password: 'admin123',
    name: 'Bambang Soeprapto, M.T.',
    email: 'admin@perusahaan.com',
    gender: 'L',
    divisionId: 'div-1',
    divisionName: 'Teknologi Informasi (IT)',
    positionId: 'pos-1',
    positionName: 'Head of Department',
    phone: '081234567890',
    status: 'aktif',
    role: 'admin',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('ADM001'),
    faceRegistered: true,
    createdAt: '2025-01-01',
  },
  {
    id: 'user-emp-1',
    nik: 'EMP001',
    username: 'budi',
    password: '123456',
    name: 'Budi Santoso',
    email: 'budi.santoso@perusahaan.com',
    gender: 'L',
    divisionId: 'div-1',
    divisionName: 'Teknologi Informasi (IT)',
    positionId: 'pos-2',
    positionName: 'Senior Software Engineer',
    phone: '081298765432',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('EMP001'),
    faceRegistered: true,
    createdAt: '2025-01-15',
  },
  {
    id: 'user-emp-2',
    nik: 'EMP002',
    username: 'siti',
    password: '123456',
    name: 'Siti Rahma',
    email: 'siti.rahma@perusahaan.com',
    gender: 'P',
    divisionId: 'div-2',
    divisionName: 'Keuangan & Akuntansi',
    positionId: 'pos-3',
    positionName: 'Financial Analyst',
    phone: '081311223344',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('EMP002'),
    faceRegistered: true,
    createdAt: '2025-02-01',
  },
  {
    id: 'user-emp-3',
    nik: 'EMP003',
    username: 'ahmad',
    password: '123456',
    name: 'Ahmad Hidayat',
    email: 'ahmad.hidayat@perusahaan.com',
    gender: 'L',
    divisionId: 'div-3',
    divisionName: 'Sumber Daya Manusia (HR)',
    positionId: 'pos-4',
    positionName: 'HR Generalist',
    phone: '081555667788',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('EMP003'),
    faceRegistered: true,
    createdAt: '2025-02-10',
  },
  {
    id: 'user-emp-4',
    nik: 'EMP004',
    username: 'dewi',
    password: '123456',
    name: 'Dewi Lestari',
    email: 'dewi.lestari@perusahaan.com',
    gender: 'P',
    divisionId: 'div-4',
    divisionName: 'Pemasaran & Media',
    positionId: 'pos-5',
    positionName: 'Digital Marketing Specialist',
    phone: '081788990011',
    status: 'aktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('EMP004'),
    faceRegistered: true,
    createdAt: '2025-03-01',
  },
  {
    id: 'user-emp-5',
    nik: 'EMP005',
    username: 'rizky',
    password: '123456',
    name: 'Rizky Pratama',
    email: 'rizky.pratama@perusahaan.com',
    gender: 'L',
    divisionId: 'div-5',
    divisionName: 'Operasional',
    positionId: 'pos-1',
    positionName: 'Head of Department',
    phone: '081233445566',
    status: 'nonaktif',
    role: 'karyawan',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300',
    faceDescriptor: generateSeedFaceDescriptor('EMP005'),
    faceRegistered: false,
    createdAt: '2025-03-05',
  }
];

// Generate seed attendance records for past few days
export function getInitialAttendances(): AttendanceRecord[] {
  const today = new Date().toISOString().split('T')[0];
  
  // Calculate dates for past days
  const getDate = (offsetDays: number) => {
    const d = new Date();
    d.setDate(d.getDate() - offsetDays);
    return d.toISOString().split('T')[0];
  };

  return [
    {
      id: 'att-1',
      employeeId: 'user-emp-1',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'masuk',
      date: today,
      serverTime: '07:48:12',
      timestamp: Date.now() - 3600000 * 4,
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      latitude: -6.175388,
      longitude: 106.827160,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 12,
      faceMatchScore: 98,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
    },
    {
      id: 'att-2',
      employeeId: 'user-emp-2',
      employeeName: 'Siti Rahma',
      nik: 'EMP002',
      divisionName: 'Keuangan & Akuntansi',
      positionName: 'Financial Analyst',
      type: 'masuk',
      date: today,
      serverTime: '08:22:45',
      timestamp: Date.now() - 3600000 * 3.5,
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
      latitude: -6.175410,
      longitude: 106.827180,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 28,
      faceMatchScore: 96,
      status: 'berhasil',
      keterangan: 'Terlambat 22 menit',
    },
    {
      id: 'att-3',
      employeeId: 'user-emp-3',
      employeeName: 'Ahmad Hidayat',
      nik: 'EMP003',
      divisionName: 'Sumber Daya Manusia (HR)',
      positionName: 'HR Generalist',
      type: 'masuk',
      date: today,
      serverTime: '07:55:02',
      timestamp: Date.now() - 3600000 * 3.8,
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      latitude: -6.175390,
      longitude: 106.827145,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 8,
      faceMatchScore: 94,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
    },
    {
      id: 'att-4',
      employeeId: 'user-emp-1',
      employeeName: 'Budi Santoso',
      nik: 'EMP001',
      divisionName: 'Teknologi Informasi (IT)',
      positionName: 'Senior Software Engineer',
      type: 'pulang',
      date: getDate(1),
      serverTime: '17:05:30',
      timestamp: Date.now() - 86400000,
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      latitude: -6.175395,
      longitude: 106.827150,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 5,
      faceMatchScore: 97,
      status: 'berhasil',
      keterangan: 'Absen Pulang Normal',
    },
    {
      id: 'att-5',
      employeeId: 'user-emp-4',
      employeeName: 'Dewi Lestari',
      nik: 'EMP004',
      divisionName: 'Pemasaran & Media',
      positionName: 'Digital Marketing Specialist',
      type: 'masuk',
      date: getDate(1),
      serverTime: '07:50:18',
      timestamp: Date.now() - 86400000 - 3600000 * 9,
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      latitude: -6.175392,
      longitude: 106.827153,
      address: 'Jl. Medan Merdeka Barat No. 17, Gambir, Jakarta Pusat',
      distanceFromOfficeMeters: 0,
      faceMatchScore: 99,
      status: 'berhasil',
      keterangan: 'Tepat Waktu',
    },
    {
      id: 'att-6',
      employeeId: 'user-emp-2',
      employeeName: 'Siti Rahma',
      nik: 'EMP002',
      divisionName: 'Keuangan & Akuntansi',
      positionName: 'Financial Analyst',
      type: 'masuk',
      date: getDate(2),
      serverTime: '08:45:00',
      timestamp: Date.now() - 86400000 * 2,
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
      latitude: -6.179000,
      longitude: 106.830000,
      address: 'Jl. Kebon Sirih No. 45, Jakarta Pusat (Di Luar Radius)',
      distanceFromOfficeMeters: 450,
      faceMatchScore: 92,
      status: 'gagal',
      keterangan: 'Gagal: Diluar radius lokasi kantor (450m > 100m)',
    }
  ];
}
